#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Sino.Droid.ContactListView.Resource.Array.date = global::Sample.Resource.Array.date;
			global::Sino.Droid.ContactListView.Resource.Attribute.sidebar_letter_color = global::Sample.Resource.Attribute.sidebar_letter_color;
			global::Sino.Droid.ContactListView.Resource.Attribute.sidebar_letter_color_selected = global::Sample.Resource.Attribute.sidebar_letter_color_selected;
			global::Sino.Droid.ContactListView.Resource.Attribute.sidebar_letter_size = global::Sample.Resource.Attribute.sidebar_letter_size;
			global::Sino.Droid.ContactListView.Resource.Attribute.sidebar_selected_bg = global::Sample.Resource.Attribute.sidebar_selected_bg;
			global::Sino.Droid.ContactListView.Resource.Attribute.text_dialog_color = global::Sample.Resource.Attribute.text_dialog_color;
			global::Sino.Droid.ContactListView.Resource.Attribute.text_dialog_size = global::Sample.Resource.Attribute.text_dialog_size;
			global::Sino.Droid.ContactListView.Resource.Color.search_edit_gray = global::Sample.Resource.Color.search_edit_gray;
			global::Sino.Droid.ContactListView.Resource.Drawable.BlankHead = global::Sample.Resource.Drawable.BlankHead;
			global::Sino.Droid.ContactListView.Resource.Drawable.edit_delete_icon = global::Sample.Resource.Drawable.edit_delete_icon;
			global::Sino.Droid.ContactListView.Resource.Drawable.edit_delete_pressed_icon = global::Sample.Resource.Drawable.edit_delete_pressed_icon;
			global::Sino.Droid.ContactListView.Resource.Drawable.emotionstore_progresscancelbtn = global::Sample.Resource.Drawable.emotionstore_progresscancelbtn;
			global::Sino.Droid.ContactListView.Resource.Drawable.item_selector = global::Sample.Resource.Drawable.item_selector;
			global::Sino.Droid.ContactListView.Resource.Drawable.itembase = global::Sample.Resource.Drawable.itembase;
			global::Sino.Droid.ContactListView.Resource.Drawable.itembasegreen = global::Sample.Resource.Drawable.itembasegreen;
			global::Sino.Droid.ContactListView.Resource.Drawable.search_edittext_shape = global::Sample.Resource.Drawable.search_edittext_shape;
			global::Sino.Droid.ContactListView.Resource.Drawable.search_icon = global::Sample.Resource.Drawable.search_icon;
			global::Sino.Droid.ContactListView.Resource.Drawable.show_head_toast_bg = global::Sample.Resource.Drawable.show_head_toast_bg;
			global::Sino.Droid.ContactListView.Resource.Drawable.sidebar_background = global::Sample.Resource.Drawable.sidebar_background;
			global::Sino.Droid.ContactListView.Resource.Id.catalog = global::Sample.Resource.Id.catalog;
			global::Sino.Droid.ContactListView.Resource.Id.contact_catalog = global::Sample.Resource.Id.contact_catalog;
			global::Sino.Droid.ContactListView.Resource.Id.contact_divider = global::Sample.Resource.Id.contact_divider;
			global::Sino.Droid.ContactListView.Resource.Id.contact_imv = global::Sample.Resource.Id.contact_imv;
			global::Sino.Droid.ContactListView.Resource.Id.contact_list_layout = global::Sample.Resource.Id.contact_list_layout;
			global::Sino.Droid.ContactListView.Resource.Id.contact_listview = global::Sample.Resource.Id.contact_listview;
			global::Sino.Droid.ContactListView.Resource.Id.contact_name = global::Sample.Resource.Id.contact_name;
			global::Sino.Droid.ContactListView.Resource.Id.dialog = global::Sample.Resource.Id.dialog;
			global::Sino.Droid.ContactListView.Resource.Id.filter_edit = global::Sample.Resource.Id.filter_edit;
			global::Sino.Droid.ContactListView.Resource.Id.sidebar = global::Sample.Resource.Id.sidebar;
			global::Sino.Droid.ContactListView.Resource.Id.title = global::Sample.Resource.Id.title;
			global::Sino.Droid.ContactListView.Resource.Layout.contact_list_item = global::Sample.Resource.Layout.contact_list_item;
			global::Sino.Droid.ContactListView.Resource.Layout.contact_list_layout = global::Sample.Resource.Layout.contact_list_layout;
			global::Sino.Droid.ContactListView.Resource.Layout.item = global::Sample.Resource.Layout.item;
			global::Sino.Droid.ContactListView.Resource.String.ApplicationName = global::Sample.Resource.String.ApplicationName;
			global::Sino.Droid.ContactListView.Resource.String.Hello = global::Sample.Resource.String.Hello;
			global::Sino.Droid.ContactListView.Resource.Style.editTextStyle = global::Sample.Resource.Style.editTextStyle;
			global::Sino.Droid.ContactListView.Resource.Style.textViewStyle = global::Sample.Resource.Style.textViewStyle;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs = global::Sample.Resource.Styleable.SideBarAttrs;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs_sidebar_letter_color = global::Sample.Resource.Styleable.SideBarAttrs_sidebar_letter_color;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs_sidebar_letter_color_selected = global::Sample.Resource.Styleable.SideBarAttrs_sidebar_letter_color_selected;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs_sidebar_letter_size = global::Sample.Resource.Styleable.SideBarAttrs_sidebar_letter_size;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs_sidebar_selected_bg = global::Sample.Resource.Styleable.SideBarAttrs_sidebar_selected_bg;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs_text_dialog_color = global::Sample.Resource.Styleable.SideBarAttrs_text_dialog_color;
			global::Sino.Droid.ContactListView.Resource.Styleable.SideBarAttrs_text_dialog_size = global::Sample.Resource.Styleable.SideBarAttrs_text_dialog_size;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int date = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int rc_emoji_code = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int rc_emoji_res = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int RCActiveColor = 2130771980;
			
			// aapt resource value: 0x7f010013
			public const int RCActiveType = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int RCCentered = 2130771984;
			
			// aapt resource value: 0x7f010007
			public const int RCCornerRadius = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int RCDefDrawable = 2130771977;
			
			// aapt resource value: 0x7f010011
			public const int RCFadeOut = 2130771985;
			
			// aapt resource value: 0x7f01000d
			public const int RCInactiveColor = 2130771981;
			
			// aapt resource value: 0x7f010012
			public const int RCInactiveType = 2130771986;
			
			// aapt resource value: 0x7f010006
			public const int RCMinShortSideSize = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public const int RCRadius = 2130771982;
			
			// aapt resource value: 0x7f010008
			public const int RCShape = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public const int RCSideBuffer = 2130771979;
			
			// aapt resource value: 0x7f010014
			public const int RCSnap = 2130771988;
			
			// aapt resource value: 0x7f01000f
			public const int RCSpacing = 2130771983;
			
			// aapt resource value: 0x7f01000a
			public const int RCStyle = 2130771978;
			
			// aapt resource value: 0x7f010002
			public const int sidebar_letter_color = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int sidebar_letter_color_selected = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int sidebar_letter_size = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int sidebar_selected_bg = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int text_dialog_color = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int text_dialog_size = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int rc_is_show_warning_notification = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int rc_play_audio_continuous = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int rc_read_receipt = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int rc_typing_status = 2131296259;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int black_textview = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int button_backgroud = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int colorAccent = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimary = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int colorPrimaryDark = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int group_list_black_textview = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int group_list_gray = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int group_list_liner = 2131034117;
			
			// aapt resource value: 0x7f050011
			public const int rc_conversation_top_bg = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int rc_draft_color = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int rc_input_bg = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int rc_message_user_name = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int rc_normal_bg = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int rc_notice_normal = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int rc_notice_text = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int rc_notice_warning = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int rc_notification_bg = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int rc_plugins_bg = 2131034130;
			
			// aapt resource value: 0x7f05000a
			public const int rc_text_color_primary = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int rc_text_color_primary_inverse = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int rc_text_color_secondary = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int rc_text_color_secondary_inverse = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int rc_text_color_tertiary = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int rc_text_voice = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int rc_voice_color = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int search_edit_gray = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0001
			public const int rc_conversation_item_data_size = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int rc_conversation_item_name_size = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int rc_message_send_status_image_size = 2131361794;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlankHead = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int demo_group_join_in = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int demo_title_back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_delete_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_delete_pressed_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int emotionstore_progresscancelbtn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int item_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int itembase = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int itembasegreen = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int rc_add_people = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int rc_an_voice_receive = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int rc_an_voice_sent = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int rc_bar_back = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rc_bar_logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rc_bar_more = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rc_bg_albums_spinner = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rc_bg_editinput = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rc_bg_item = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int rc_bg_menu = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int rc_bg_text_hover = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int rc_bg_text_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int rc_bg_voice_popup = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int rc_btn_input = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int rc_btn_pub_service_enter_hover = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int rc_btn_pub_service_enter_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int rc_btn_pub_service_follow_hover = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int rc_btn_pub_service_follow_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rc_btn_public_service_enter_selector = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int rc_btn_public_service_unfollow_selector = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int rc_btn_send = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int rc_btn_send_hover = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int rc_btn_send_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int rc_btn_voice = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int rc_btn_voice_hover = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int rc_btn_voice_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int rc_checkbox_normal = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int rc_checkbox_pressed = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int rc_conversation_list_msg_send_failure = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int rc_conversation_list_msg_sending = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int rc_conversation_newmsg = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int rc_default_discussion_portrait = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int rc_default_group_portrait = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int rc_default_portrait = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int rc_ed_pub_service_search_hover = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int rc_ed_pub_service_search_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int rc_ed_public_service_search_selector = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int rc_group_default_portrait = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int rc_ic_admin_selector = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int rc_ic_albums_checked = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int rc_ic_albums_normal = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int rc_ic_bubble_left = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int rc_ic_bubble_no_left = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int rc_ic_bubble_no_right = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int rc_ic_bubble_right = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int rc_ic_bubble_white = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int rc_ic_camera = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int rc_ic_def_coversation_portrait = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int rc_ic_def_coversation_portrait2 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int rc_ic_def_msg_portrait = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int rc_ic_def_rich_content = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int rc_ic_delete = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int rc_ic_emoji_block = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int rc_ic_extend = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int rc_ic_extend_normal = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int rc_ic_extend_selected = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int rc_ic_keyboard = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int rc_ic_keyboard_normal = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int rc_ic_keyboard_selected = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int rc_ic_location = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int rc_ic_location_item_default = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int rc_ic_menu_keyboard = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int rc_ic_message_block = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int rc_ic_no = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int rc_ic_no_hover = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int rc_ic_no_selector = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int rc_ic_notice_loading = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int rc_ic_notice_point = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int rc_ic_notice_wraning = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int rc_ic_phone = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int rc_ic_picture = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int rc_ic_setting_friends_add = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int rc_ic_setting_friends_delete = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int rc_ic_smiley = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int rc_ic_smiley_normal = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int rc_ic_smiley_selected = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int rc_ic_star = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int rc_ic_star_hover = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int rc_ic_star_selector = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int rc_ic_text = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int rc_ic_trangle = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int rc_ic_voice = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int rc_ic_voice_normal = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int rc_ic_voice_receive = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int rc_ic_voice_receive_play1 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int rc_ic_voice_receive_play2 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int rc_ic_voice_receive_play3 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int rc_ic_voice_selected = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int rc_ic_voice_sent = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int rc_ic_voice_sent_play1 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int rc_ic_voice_sent_play2 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int rc_ic_voice_sent_play3 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int rc_ic_volume_1 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int rc_ic_volume_2 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int rc_ic_volume_3 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int rc_ic_volume_4 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int rc_ic_volume_5 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int rc_ic_volume_6 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int rc_ic_volume_7 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int rc_ic_volume_8 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int rc_ic_volume_cancel = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int rc_ic_volume_wraning = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int rc_ic_warning = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int rc_ic_yes = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int rc_ic_yes_hover = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int rc_ic_yes_selector = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int rc_icon_admin = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int rc_icon_admin_hover = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int rc_img_camera = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int rc_item_list_selector = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int rc_item_top_list_selector = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int rc_loading = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int rc_mebmer_delete = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int rc_notification_network_available = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int rc_photo_checkbox = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int rc_precheckbox_normal = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int rc_precheckbox_pressed = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int rc_preview_checkbox = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int rc_progress_sending_style = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int rc_public_service_menu_bg = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int rc_radio_button_off = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int rc_radio_button_on = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int rc_read_receipt = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int rc_receive_voice_one = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int rc_receive_voice_three = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int rc_receive_voice_two = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int rc_send_voice_one = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int rc_send_voice_three = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int rc_send_voice_two = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int rc_switch_btn = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int rc_unread_count_bg = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int rc_unread_message_count = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int rc_unread_remind_without_count = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int rc_voice_icon_left = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int rc_voice_icon_right = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int rc_voice_unread = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int rc_voide_message_unread = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int rc_volume_four = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int rc_volume_one = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int rc_volume_three = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int rc_volume_two = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int rc_volume_zero = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int search_edittext_shape = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int search_icon = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int show_head_toast_bg = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int sidebar_background = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int u1f004 = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int u1f30f = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int u1f319 = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int u1f332 = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int u1f339 = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int u1f33b = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int u1f349 = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int u1f356 = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int u1f35a = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int u1f366 = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int u1f36b = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int u1f377 = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int u1f37b = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int u1f381 = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int u1f382 = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int u1f384 = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int u1f389 = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int u1f393 = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int u1f3a4 = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int u1f3b2 = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int u1f3b5 = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int u1f3c0 = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int u1f3c2 = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int u1f3e1 = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int u1f434 = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int u1f436 = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int u1f437 = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int u1f44a = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int u1f44c = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int u1f44d = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int u1f44e = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int u1f44f = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int u1f451 = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int u1f46a = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int u1f46b = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int u1f47b = 2130837695;
			
			// aapt resource value: 0x7f0200c0
			public const int u1f47c = 2130837696;
			
			// aapt resource value: 0x7f0200c1
			public const int u1f47d = 2130837697;
			
			// aapt resource value: 0x7f0200c2
			public const int u1f47f = 2130837698;
			
			// aapt resource value: 0x7f0200c3
			public const int u1f484 = 2130837699;
			
			// aapt resource value: 0x7f0200c4
			public const int u1f48a = 2130837700;
			
			// aapt resource value: 0x7f0200c5
			public const int u1f48b = 2130837701;
			
			// aapt resource value: 0x7f0200c6
			public const int u1f48d = 2130837702;
			
			// aapt resource value: 0x7f0200c7
			public const int u1f494 = 2130837703;
			
			// aapt resource value: 0x7f0200c8
			public const int u1f4a1 = 2130837704;
			
			// aapt resource value: 0x7f0200c9
			public const int u1f4a2 = 2130837705;
			
			// aapt resource value: 0x7f0200ca
			public const int u1f4a3 = 2130837706;
			
			// aapt resource value: 0x7f0200cb
			public const int u1f4a4 = 2130837707;
			
			// aapt resource value: 0x7f0200cc
			public const int u1f4a9 = 2130837708;
			
			// aapt resource value: 0x7f0200cd
			public const int u1f4aa = 2130837709;
			
			// aapt resource value: 0x7f0200ce
			public const int u1f4b0 = 2130837710;
			
			// aapt resource value: 0x7f0200cf
			public const int u1f4da = 2130837711;
			
			// aapt resource value: 0x7f0200d0
			public const int u1f4de = 2130837712;
			
			// aapt resource value: 0x7f0200d1
			public const int u1f4e2 = 2130837713;
			
			// aapt resource value: 0x7f0200d2
			public const int u1f525 = 2130837714;
			
			// aapt resource value: 0x7f0200d3
			public const int u1f52b = 2130837715;
			
			// aapt resource value: 0x7f0200d4
			public const int u1f556 = 2130837716;
			
			// aapt resource value: 0x7f0200d5
			public const int u1f600 = 2130837717;
			
			// aapt resource value: 0x7f0200d6
			public const int u1f601 = 2130837718;
			
			// aapt resource value: 0x7f0200d7
			public const int u1f602 = 2130837719;
			
			// aapt resource value: 0x7f0200d8
			public const int u1f603 = 2130837720;
			
			// aapt resource value: 0x7f0200d9
			public const int u1f605 = 2130837721;
			
			// aapt resource value: 0x7f0200da
			public const int u1f606 = 2130837722;
			
			// aapt resource value: 0x7f0200db
			public const int u1f607 = 2130837723;
			
			// aapt resource value: 0x7f0200dc
			public const int u1f608 = 2130837724;
			
			// aapt resource value: 0x7f0200dd
			public const int u1f609 = 2130837725;
			
			// aapt resource value: 0x7f0200de
			public const int u1f60a = 2130837726;
			
			// aapt resource value: 0x7f0200df
			public const int u1f60b = 2130837727;
			
			// aapt resource value: 0x7f0200e0
			public const int u1f60c = 2130837728;
			
			// aapt resource value: 0x7f0200e1
			public const int u1f60d = 2130837729;
			
			// aapt resource value: 0x7f0200e2
			public const int u1f60e = 2130837730;
			
			// aapt resource value: 0x7f0200e3
			public const int u1f60f = 2130837731;
			
			// aapt resource value: 0x7f0200e4
			public const int u1f611 = 2130837732;
			
			// aapt resource value: 0x7f0200e5
			public const int u1f612 = 2130837733;
			
			// aapt resource value: 0x7f0200e6
			public const int u1f613 = 2130837734;
			
			// aapt resource value: 0x7f0200e7
			public const int u1f614 = 2130837735;
			
			// aapt resource value: 0x7f0200e8
			public const int u1f615 = 2130837736;
			
			// aapt resource value: 0x7f0200e9
			public const int u1f616 = 2130837737;
			
			// aapt resource value: 0x7f0200ea
			public const int u1f618 = 2130837738;
			
			// aapt resource value: 0x7f0200eb
			public const int u1f61a = 2130837739;
			
			// aapt resource value: 0x7f0200ec
			public const int u1f61c = 2130837740;
			
			// aapt resource value: 0x7f0200ed
			public const int u1f61d = 2130837741;
			
			// aapt resource value: 0x7f0200ee
			public const int u1f61e = 2130837742;
			
			// aapt resource value: 0x7f0200ef
			public const int u1f61f = 2130837743;
			
			// aapt resource value: 0x7f0200f0
			public const int u1f621 = 2130837744;
			
			// aapt resource value: 0x7f0200f1
			public const int u1f622 = 2130837745;
			
			// aapt resource value: 0x7f0200f2
			public const int u1f623 = 2130837746;
			
			// aapt resource value: 0x7f0200f3
			public const int u1f624 = 2130837747;
			
			// aapt resource value: 0x7f0200f4
			public const int u1f628 = 2130837748;
			
			// aapt resource value: 0x7f0200f5
			public const int u1f629 = 2130837749;
			
			// aapt resource value: 0x7f0200f6
			public const int u1f62a = 2130837750;
			
			// aapt resource value: 0x7f0200f7
			public const int u1f62b = 2130837751;
			
			// aapt resource value: 0x7f0200f8
			public const int u1f62c = 2130837752;
			
			// aapt resource value: 0x7f0200f9
			public const int u1f62d = 2130837753;
			
			// aapt resource value: 0x7f0200fa
			public const int u1f62e = 2130837754;
			
			// aapt resource value: 0x7f0200fb
			public const int u1f62f = 2130837755;
			
			// aapt resource value: 0x7f0200fc
			public const int u1f630 = 2130837756;
			
			// aapt resource value: 0x7f0200fd
			public const int u1f631 = 2130837757;
			
			// aapt resource value: 0x7f0200fe
			public const int u1f632 = 2130837758;
			
			// aapt resource value: 0x7f0200ff
			public const int u1f633 = 2130837759;
			
			// aapt resource value: 0x7f020100
			public const int u1f634 = 2130837760;
			
			// aapt resource value: 0x7f020101
			public const int u1f635 = 2130837761;
			
			// aapt resource value: 0x7f020102
			public const int u1f636 = 2130837762;
			
			// aapt resource value: 0x7f020103
			public const int u1f637 = 2130837763;
			
			// aapt resource value: 0x7f020104
			public const int u1f648 = 2130837764;
			
			// aapt resource value: 0x7f020105
			public const int u1f649 = 2130837765;
			
			// aapt resource value: 0x7f020106
			public const int u1f64a = 2130837766;
			
			// aapt resource value: 0x7f020107
			public const int u1f64f = 2130837767;
			
			// aapt resource value: 0x7f020108
			public const int u1f680 = 2130837768;
			
			// aapt resource value: 0x7f020109
			public const int u1f6ab = 2130837769;
			
			// aapt resource value: 0x7f02010a
			public const int u1f6b2 = 2130837770;
			
			// aapt resource value: 0x7f02010b
			public const int u1f6bf = 2130837771;
			
			// aapt resource value: 0x7f02010c
			public const int u23f0 = 2130837772;
			
			// aapt resource value: 0x7f02010d
			public const int u23f3 = 2130837773;
			
			// aapt resource value: 0x7f02010e
			public const int u2600 = 2130837774;
			
			// aapt resource value: 0x7f02010f
			public const int u2601 = 2130837775;
			
			// aapt resource value: 0x7f020110
			public const int u2614 = 2130837776;
			
			// aapt resource value: 0x7f020111
			public const int u2615 = 2130837777;
			
			// aapt resource value: 0x7f020112
			public const int u261d = 2130837778;
			
			// aapt resource value: 0x7f020113
			public const int u263a = 2130837779;
			
			// aapt resource value: 0x7f020114
			public const int u26a1 = 2130837780;
			
			// aapt resource value: 0x7f020115
			public const int u26bd = 2130837781;
			
			// aapt resource value: 0x7f020116
			public const int u26c4 = 2130837782;
			
			// aapt resource value: 0x7f020117
			public const int u26c5 = 2130837783;
			
			// aapt resource value: 0x7f020118
			public const int u270a = 2130837784;
			
			// aapt resource value: 0x7f020119
			public const int u270b = 2130837785;
			
			// aapt resource value: 0x7f02011a
			public const int u270c = 2130837786;
			
			// aapt resource value: 0x7f02011b
			public const int u270f = 2130837787;
			
			// aapt resource value: 0x7f02011c
			public const int u2744 = 2130837788;
			
			// aapt resource value: 0x7f02011d
			public const int u2b50 = 2130837789;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0035
			public const int C = 2131427381;
			
			// aapt resource value: 0x7f0b0036
			public const int CE = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int CES = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int CS = 2131427384;
			
			// aapt resource value: 0x7f0b0039
			public const int CSE = 2131427385;
			
			// aapt resource value: 0x7f0b003a
			public const int EC = 2131427386;
			
			// aapt resource value: 0x7f0b003b
			public const int ECS = 2131427387;
			
			// aapt resource value: 0x7f0b005b
			public const int MyButton = 2131427419;
			
			// aapt resource value: 0x7f0b003e
			public const int RCFill = 2131427390;
			
			// aapt resource value: 0x7f0b003f
			public const int RCStroke = 2131427391;
			
			// aapt resource value: 0x7f0b003c
			public const int SC = 2131427388;
			
			// aapt resource value: 0x7f0b003d
			public const int SCE = 2131427389;
			
			// aapt resource value: 0x7f0b006c
			public const int account = 2131427436;
			
			// aapt resource value: 0x7f0b004b
			public const int back = 2131427403;
			
			// aapt resource value: 0x7f0b005c
			public const int btn_cancel = 2131427420;
			
			// aapt resource value: 0x7f0b005e
			public const int btn_isOK = 2131427422;
			
			// aapt resource value: 0x7f0b0058
			public const int catalog = 2131427416;
			
			// aapt resource value: 0x7f0b0033
			public const int circle = 2131427379;
			
			// aapt resource value: 0x7f0b0040
			public const int contact_catalog = 2131427392;
			
			// aapt resource value: 0x7f0b0041
			public const int contact_divider = 2131427393;
			
			// aapt resource value: 0x7f0b0042
			public const int contact_imv = 2131427394;
			
			// aapt resource value: 0x7f0b0045
			public const int contact_list_layout = 2131427397;
			
			// aapt resource value: 0x7f0b0046
			public const int contact_listview = 2131427398;
			
			// aapt resource value: 0x7f0b0043
			public const int contact_name = 2131427395;
			
			// aapt resource value: 0x7f0b0051
			public const int conversation = 2131427409;
			
			// aapt resource value: 0x7f0b0049
			public const int conversationlist = 2131427401;
			
			// aapt resource value: 0x7f0b0052
			public const int demo_contactlist = 2131427410;
			
			// aapt resource value: 0x7f0b006f
			public const int description = 2131427439;
			
			// aapt resource value: 0x7f0b0047
			public const int dialog = 2131427399;
			
			// aapt resource value: 0x7f0b0070
			public const int enter = 2131427440;
			
			// aapt resource value: 0x7f0b0044
			public const int filter_edit = 2131427396;
			
			// aapt resource value: 0x7f0b0071
			public const int follow = 2131427441;
			
			// aapt resource value: 0x7f0b006e
			public const int func = 2131427438;
			
			// aapt resource value: 0x7f0b004c
			public const int img1 = 2131427404;
			
			// aapt resource value: 0x7f0b004e
			public const int img3 = 2131427406;
			
			// aapt resource value: 0x7f0b007b
			public const int introduction = 2131427451;
			
			// aapt resource value: 0x7f0b005a
			public const int mBtn1 = 2131427418;
			
			// aapt resource value: 0x7f0b006b
			public const int name = 2131427435;
			
			// aapt resource value: 0x7f0b0056
			public const int personal_id = 2131427414;
			
			// aapt resource value: 0x7f0b0055
			public const int personal_name = 2131427413;
			
			// aapt resource value: 0x7f0b0054
			public const int personal_portrait = 2131427412;
			
			// aapt resource value: 0x7f0b006a
			public const int portrait = 2131427434;
			
			// aapt resource value: 0x7f0b000b
			public const int rc_actionbar = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int rc_back = 2131427338;
			
			// aapt resource value: 0x7f0b002b
			public const int rc_btn_cancel = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int rc_btn_ok = 2131427372;
			
			// aapt resource value: 0x7f0b0060
			public const int rc_chebox_pictrue = 2131427424;
			
			// aapt resource value: 0x7f0b002a
			public const int rc_checkbox = 2131427370;
			
			// aapt resource value: 0x7f0b0005
			public const int rc_content = 2131427333;
			
			// aapt resource value: 0x7f0b0020
			public const int rc_conversation_content = 2131427360;
			
			// aapt resource value: 0x7f0b0022
			public const int rc_conversation_msg_block = 2131427362;
			
			// aapt resource value: 0x7f0b0032
			public const int rc_conversation_status = 2131427378;
			
			// aapt resource value: 0x7f0b0021
			public const int rc_conversation_time = 2131427361;
			
			// aapt resource value: 0x7f0b001f
			public const int rc_conversation_title = 2131427359;
			
			// aapt resource value: 0x7f0b0064
			public const int rc_cs_msg = 2131427428;
			
			// aapt resource value: 0x7f0b0062
			public const int rc_cs_stars = 2131427426;
			
			// aapt resource value: 0x7f0b0063
			public const int rc_cs_yes_no = 2131427427;
			
			// aapt resource value: 0x7f0b0086
			public const int rc_ext = 2131427462;
			
			// aapt resource value: 0x7f0b007d
			public const int rc_flow = 2131427453;
			
			// aapt resource value: 0x7f0b002f
			public const int rc_fragment = 2131427375;
			
			// aapt resource value: 0x7f0b0030
			public const int rc_frame = 2131427376;
			
			// aapt resource value: 0x7f0b0000
			public const int rc_icon = 2131427328;
			
			// aapt resource value: 0x7f0b0004
			public const int rc_img = 2131427332;
			
			// aapt resource value: 0x7f0b007e
			public const int rc_indicator = 2131427454;
			
			// aapt resource value: 0x7f0b0066
			public const int rc_input = 2131427430;
			
			// aapt resource value: 0x7f0b0084
			public const int rc_input_custom_menu = 2131427460;
			
			// aapt resource value: 0x7f0b0029
			public const int rc_input_extension = 2131427369;
			
			// aapt resource value: 0x7f0b0028
			public const int rc_input_main = 2131427368;
			
			// aapt resource value: 0x7f0b0082
			public const int rc_input_menu = 2131427458;
			
			// aapt resource value: 0x7f0b0027
			public const int rc_input_switch = 2131427367;
			
			// aapt resource value: 0x7f0b0010
			public const int rc_item0 = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int rc_item1 = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int rc_item2 = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int rc_item3 = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int rc_item4 = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int rc_item5 = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int rc_item6 = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int rc_item7 = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int rc_item8 = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int rc_item9 = 2131427353;
			
			// aapt resource value: 0x7f0b0025
			public const int rc_item_conversation = 2131427365;
			
			// aapt resource value: 0x7f0b0006
			public const int rc_layout = 2131427334;
			
			// aapt resource value: 0x7f0b001a
			public const int rc_left = 2131427354;
			
			// aapt resource value: 0x7f0b0001
			public const int rc_list = 2131427329;
			
			// aapt resource value: 0x7f0b000c
			public const int rc_logo = 2131427340;
			
			// aapt resource value: 0x7f0b0079
			public const int rc_menu_item_text = 2131427449;
			
			// aapt resource value: 0x7f0b007a
			public const int rc_menu_line = 2131427450;
			
			// aapt resource value: 0x7f0b0080
			public const int rc_menu_switch = 2131427456;
			
			// aapt resource value: 0x7f0b0026
			public const int rc_message_send_failed = 2131427366;
			
			// aapt resource value: 0x7f0b0003
			public const int rc_msg = 2131427331;
			
			// aapt resource value: 0x7f0b000e
			public const int rc_new = 2131427342;
			
			// aapt resource value: 0x7f0b0068
			public const int rc_new_message_count = 2131427432;
			
			// aapt resource value: 0x7f0b0069
			public const int rc_new_message_number = 2131427433;
			
			// aapt resource value: 0x7f0b002d
			public const int rc_pager = 2131427373;
			
			// aapt resource value: 0x7f0b0085
			public const int rc_plugins = 2131427461;
			
			// aapt resource value: 0x7f0b001d
			public const int rc_portrait = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int rc_portrait_right = 2131427358;
			
			// aapt resource value: 0x7f0b0007
			public const int rc_progress = 2131427335;
			
			// aapt resource value: 0x7f0b0009
			public const int rc_read_receipt = 2131427337;
			
			// aapt resource value: 0x7f0b001b
			public const int rc_right = 2131427355;
			
			// aapt resource value: 0x7f0b0074
			public const int rc_search_btn = 2131427444;
			
			// aapt resource value: 0x7f0b0073
			public const int rc_search_ed = 2131427443;
			
			// aapt resource value: 0x7f0b0075
			public const int rc_search_list = 2131427445;
			
			// aapt resource value: 0x7f0b002e
			public const int rc_send = 2131427374;
			
			// aapt resource value: 0x7f0b0031
			public const int rc_sent_status = 2131427377;
			
			// aapt resource value: 0x7f0b0076
			public const int rc_setting_item = 2131427446;
			
			// aapt resource value: 0x7f0b0065
			public const int rc_status_bar = 2131427429;
			
			// aapt resource value: 0x7f0b007f
			public const int rc_switcher = 2131427455;
			
			// aapt resource value: 0x7f0b0081
			public const int rc_switcher1 = 2131427457;
			
			// aapt resource value: 0x7f0b0083
			public const int rc_switcher2 = 2131427459;
			
			// aapt resource value: 0x7f0b001c
			public const int rc_time = 2131427356;
			
			// aapt resource value: 0x7f0b000d
			public const int rc_title = 2131427341;
			
			// aapt resource value: 0x7f0b000f
			public const int rc_title_layout = 2131427343;
			
			// aapt resource value: 0x7f0b0002
			public const int rc_txt = 2131427330;
			
			// aapt resource value: 0x7f0b0023
			public const int rc_unread_message = 2131427363;
			
			// aapt resource value: 0x7f0b0067
			public const int rc_unread_message_count = 2131427431;
			
			// aapt resource value: 0x7f0b0077
			public const int rc_unread_message_icon = 2131427447;
			
			// aapt resource value: 0x7f0b0078
			public const int rc_unread_message_icon_right = 2131427448;
			
			// aapt resource value: 0x7f0b0024
			public const int rc_unread_message_right = 2131427364;
			
			// aapt resource value: 0x7f0b007c
			public const int rc_voice_unread = 2131427452;
			
			// aapt resource value: 0x7f0b0008
			public const int rc_warning = 2131427336;
			
			// aapt resource value: 0x7f0b0061
			public const int rc_webview = 2131427425;
			
			// aapt resource value: 0x7f0b006d
			public const int rel_group_intro = 2131427437;
			
			// aapt resource value: 0x7f0b004a
			public const int rl = 2131427402;
			
			// aapt resource value: 0x7f0b0057
			public const int send_message = 2131427415;
			
			// aapt resource value: 0x7f0b005d
			public const int show_pictrue = 2131427421;
			
			// aapt resource value: 0x7f0b005f
			public const int shownumber = 2131427423;
			
			// aapt resource value: 0x7f0b0048
			public const int sidebar = 2131427400;
			
			// aapt resource value: 0x7f0b0034
			public const int square = 2131427380;
			
			// aapt resource value: 0x7f0b004f
			public const int startChatBtn = 2131427407;
			
			// aapt resource value: 0x7f0b0050
			public const int startGroupBtn = 2131427408;
			
			// aapt resource value: 0x7f0b0059
			public const int title = 2131427417;
			
			// aapt resource value: 0x7f0b004d
			public const int txt1 = 2131427405;
			
			// aapt resource value: 0x7f0b0072
			public const int unfollow = 2131427442;
			
			// aapt resource value: 0x7f0b0053
			public const int viewPager = 2131427411;
			
			// aapt resource value: 0x7f0b0087
			public const int volume_animation = 2131427463;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080002
			public const int rc_audio_encoding_bit_rate = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int rc_chatroom_first_pull_message_count = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int rc_custom_service_evaluation_interval = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int rc_image_quality = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int rc_image_size = 2131230724;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int contact_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int contact_list_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConverSationList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int demo_actionbar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int demo_chat = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int demo_conversation = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int demo_friendList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int demo_home = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int demo_personalDetail = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int item = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int rc_ac_albums = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int rc_ac_camera = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int rc_ac_preview = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int rc_ac_selected_pictrue = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int rc_ac_webview = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int rc_activity = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int rc_cs_alert_human_evaluation = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int rc_cs_alert_robot_evaluation = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int rc_cs_alert_warning = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int rc_fr_conversation = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int rc_fr_conversation_member_list = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int rc_fr_conversationlist = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int rc_fr_dialog_alter = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int rc_fr_messageinput = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int rc_fr_messagelist = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int rc_fr_photo = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int rc_fr_photo2 = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int rc_fr_public_service_inf = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int rc_fr_public_service_search = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int rc_fr_public_service_sub_list = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int rc_fr_test = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int rc_fragment_base_setting = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int rc_item_albums = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int rc_item_app_service_conversation = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int rc_item_base_conversation = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int rc_item_conversation = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int rc_item_conversation_member = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int rc_item_discussion_conversation = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int rc_item_discussion_notification_message = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int rc_item_group_conversation = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int rc_item_image_message = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int rc_item_information_notification_message = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int rc_item_location_message = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int rc_item_message = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int rc_item_preview_fragment = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int rc_item_progress = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int rc_item_public_service_conversation = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int rc_item_public_service_input_menu = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int rc_item_public_service_input_menu_item = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int rc_item_public_service_input_menus = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int rc_item_public_service_list = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int rc_item_public_service_message = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int rc_item_public_service_multi_rich_content_message = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int rc_item_public_service_rich_content_message = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int rc_item_public_service_search = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int rc_item_rich_content_message = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int rc_item_system_conversation = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int rc_item_text_message = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int rc_item_voice_message = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int rc_ui_voice_cover = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int rc_wi_block = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int rc_wi_block_popup = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int rc_wi_emoji_grid = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int rc_wi_emoji_txt = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int rc_wi_ext_pager = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int rc_wi_input = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int rc_wi_notice = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int rc_wi_notification_loading = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int rc_wi_plugins = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int rc_wi_text_btn = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int rc_wi_txt_provider = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int rc_wi_vo_popup = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int rc_wi_vo_provider = 2130903113;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060070
			public const int add_friend = 2131099760;
			
			// aapt resource value: 0x7f06006f
			public const int personal_send_message = 2131099759;
			
			// aapt resource value: 0x7f060062
			public const int rc_called_accept = 2131099746;
			
			// aapt resource value: 0x7f06005e
			public const int rc_called_is_calling = 2131099742;
			
			// aapt resource value: 0x7f060061
			public const int rc_called_not_accept = 2131099745;
			
			// aapt resource value: 0x7f06005d
			public const int rc_called_on_hook = 2131099741;
			
			// aapt resource value: 0x7f06001c
			public const int rc_conversation_List_operation_failure = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int rc_conversation_list_app_public_service = 2131099669;
			
			// aapt resource value: 0x7f06001d
			public const int rc_conversation_list_default_discussion_name = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int rc_conversation_list_dialog_cancel_top = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int rc_conversation_list_dialog_remove = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int rc_conversation_list_dialog_set_top = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int rc_conversation_list_empty_prompt = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int rc_conversation_list_my_chatroom = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int rc_conversation_list_my_customer_service = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int rc_conversation_list_my_discussion = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int rc_conversation_list_my_group = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int rc_conversation_list_my_private_conversation = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int rc_conversation_list_not_connected = 2131099679;
			
			// aapt resource value: 0x7f06001b
			public const int rc_conversation_list_popup_cancel_top = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int rc_conversation_list_popup_set_top = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int rc_conversation_list_public_service = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int rc_conversation_list_system_conversation = 2131099668;
			
			// aapt resource value: 0x7f060069
			public const int rc_cs_cancel = 2131099753;
			
			// aapt resource value: 0x7f060066
			public const int rc_cs_evaluate_human = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int rc_cs_evaluate_robot = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int rc_cs_submit = 2131099752;
			
			// aapt resource value: 0x7f060033
			public const int rc_dialog_cancel = 2131099699;
			
			// aapt resource value: 0x7f060026
			public const int rc_dialog_item_message_copy = 2131099686;
			
			// aapt resource value: 0x7f060025
			public const int rc_dialog_item_message_delete = 2131099685;
			
			// aapt resource value: 0x7f060034
			public const int rc_dialog_ok = 2131099700;
			
			// aapt resource value: 0x7f060008
			public const int rc_discussion_nt_msg_for_add = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int rc_discussion_nt_msg_for_added = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int rc_discussion_nt_msg_for_exit = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int rc_discussion_nt_msg_for_is_open_invite_close = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int rc_discussion_nt_msg_for_is_open_invite_open = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int rc_discussion_nt_msg_for_removed = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int rc_discussion_nt_msg_for_rename = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int rc_discussion_nt_msg_for_who_removed = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int rc_discussion_nt_msg_for_you = 2131099660;
			
			// aapt resource value: 0x7f06005f
			public const int rc_exit_calling = 2131099743;
			
			// aapt resource value: 0x7f060059
			public const int rc_file_not_exist = 2131099737;
			
			// aapt resource value: 0x7f060054
			public const int rc_forbidden_in_chatroom = 2131099732;
			
			// aapt resource value: 0x7f060053
			public const int rc_info_forbidden_to_talk = 2131099731;
			
			// aapt resource value: 0x7f060051
			public const int rc_info_not_in_chatroom = 2131099729;
			
			// aapt resource value: 0x7f06004f
			public const int rc_info_not_in_discussion = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int rc_info_not_in_group = 2131099728;
			
			// aapt resource value: 0x7f06006e
			public const int rc_init_failed = 2131099758;
			
			// aapt resource value: 0x7f060035
			public const int rc_input_send = 2131099701;
			
			// aapt resource value: 0x7f060028
			public const int rc_input_voice = 2131099688;
			
			// aapt resource value: 0x7f060055
			public const int rc_kicked_from_chatroom = 2131099733;
			
			// aapt resource value: 0x7f060024
			public const int rc_message_content_draft = 2131099684;
			
			// aapt resource value: 0x7f060020
			public const int rc_message_content_image = 2131099680;
			
			// aapt resource value: 0x7f060023
			public const int rc_message_content_location = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int rc_message_content_rich_text = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int rc_message_content_voice = 2131099681;
			
			// aapt resource value: 0x7f06004e
			public const int rc_message_unknown = 2131099726;
			
			// aapt resource value: 0x7f060027
			public const int rc_message_unread_count = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int rc_name = 2131099650;
			
			// aapt resource value: 0x7f06005b
			public const int rc_network_error = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int rc_network_exception = 2131099740;
			
			// aapt resource value: 0x7f06005a
			public const int rc_network_is_busy = 2131099738;
			
			// aapt resource value: 0x7f060045
			public const int rc_notice_connecting = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int rc_notice_create_discussion = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int rc_notice_create_discussion_fail = 2131099719;
			
			// aapt resource value: 0x7f06004a
			public const int rc_notice_data_is_loading = 2131099722;
			
			// aapt resource value: 0x7f060043
			public const int rc_notice_disconnect = 2131099715;
			
			// aapt resource value: 0x7f06004c
			public const int rc_notice_download_fail = 2131099724;
			
			// aapt resource value: 0x7f060048
			public const int rc_notice_enter_chatroom = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int rc_notice_input_conversation_error = 2131099721;
			
			// aapt resource value: 0x7f06004b
			public const int rc_notice_load_data_fail = 2131099723;
			
			// aapt resource value: 0x7f060042
			public const int rc_notice_network_unavailable = 2131099714;
			
			// aapt resource value: 0x7f06004d
			public const int rc_notice_select_one_picture_at_last = 2131099725;
			
			// aapt resource value: 0x7f060044
			public const int rc_notice_tick = 2131099716;
			
			// aapt resource value: 0x7f06006b
			public const int rc_notification_new_msg = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int rc_notification_new_plural_msg = 2131099756;
			
			// aapt resource value: 0x7f06006a
			public const int rc_notification_ticker_text = 2131099754;
			
			// aapt resource value: 0x7f060038
			public const int rc_plugins_camera = 2131099704;
			
			// aapt resource value: 0x7f060037
			public const int rc_plugins_image = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int rc_plugins_location = 2131099702;
			
			// aapt resource value: 0x7f060063
			public const int rc_plugins_voip = 2131099747;
			
			// aapt resource value: 0x7f060041
			public const int rc_pub_service_info_account = 2131099713;
			
			// aapt resource value: 0x7f06003d
			public const int rc_pub_service_info_description = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int rc_pub_service_info_enter = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int rc_pub_service_info_follow = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int rc_pub_service_info_unfollow = 2131099712;
			
			// aapt resource value: 0x7f06006d
			public const int rc_quit_custom_service = 2131099757;
			
			// aapt resource value: 0x7f060064
			public const int rc_read_all = 2131099748;
			
			// aapt resource value: 0x7f060052
			public const int rc_rejected_by_blacklist_prompt = 2131099730;
			
			// aapt resource value: 0x7f060056
			public const int rc_send_format = 2131099734;
			
			// aapt resource value: 0x7f06002c
			public const int rc_setting_clear_msg_fail = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int rc_setting_clear_msg_name = 2131099691;
			
			// aapt resource value: 0x7f06002a
			public const int rc_setting_clear_msg_prompt = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int rc_setting_clear_msg_success = 2131099693;
			
			// aapt resource value: 0x7f060030
			public const int rc_setting_conversation_notify = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int rc_setting_conversation_notify_fail = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int rc_setting_get_conversation_notify_fail = 2131099698;
			
			// aapt resource value: 0x7f060029
			public const int rc_setting_name = 2131099689;
			
			// aapt resource value: 0x7f06002e
			public const int rc_setting_set_top = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int rc_setting_set_top_fail = 2131099695;
			
			// aapt resource value: 0x7f06003a
			public const int rc_voice_cancel = 2131099706;
			
			// aapt resource value: 0x7f060004
			public const int rc_voice_dialog_cancel_send = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int rc_voice_dialog_swipe = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int rc_voice_dialog_time_short = 2131099653;
			
			// aapt resource value: 0x7f06003c
			public const int rc_voice_failure = 2131099708;
			
			// aapt resource value: 0x7f060039
			public const int rc_voice_rec = 2131099705;
			
			// aapt resource value: 0x7f06003b
			public const int rc_voice_short = 2131099707;
			
			// aapt resource value: 0x7f060065
			public const int rc_voip_cpu_error = 2131099749;
			
			// aapt resource value: 0x7f060058
			public const int rc_waiting = 2131099736;
			
			// aapt resource value: 0x7f060060
			public const int rc_yes = 2131099744;
			
			// aapt resource value: 0x7f060057
			public const int rc_yesterday_format = 2131099735;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070012
			public const int DemoTextStyleBigBlack = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int DemoTextStyleMiddle = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int RCTheme = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int RCTheme_Message_RichContent_TextView = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int RCTheme_Message_TextView = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int RCTheme_Message_Username_TextView = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int RCTheme_Notification = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int RCTheme_TextView = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int RCTheme_TextView_Large = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int RCTheme_TextView_Large_Inverse = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int RCTheme_TextView_Medium = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int RCTheme_TextView_New = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int RCTheme_TextView_Small = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int RcDialog = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int custom_checkbox = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int editTextStyle = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int horizontal_light_thin_divider = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int preview_checkbox = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int textViewStyle = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int vertical_light_thin_divider = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AsyncImageView = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int AsyncImageView_RCCornerRadius = 1;
			
			// aapt resource value: 3
			public const int AsyncImageView_RCDefDrawable = 3;
			
			// aapt resource value: 0
			public const int AsyncImageView_RCMinShortSideSize = 0;
			
			// aapt resource value: 2
			public const int AsyncImageView_RCShape = 2;
			
			public static int[] InputView = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int InputView_RCStyle = 0;
			
			public static int[] RCCircleFlowIndicator = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int RCCircleFlowIndicator_RCActiveColor = 0;
			
			// aapt resource value: 7
			public const int RCCircleFlowIndicator_RCActiveType = 7;
			
			// aapt resource value: 4
			public const int RCCircleFlowIndicator_RCCentered = 4;
			
			// aapt resource value: 5
			public const int RCCircleFlowIndicator_RCFadeOut = 5;
			
			// aapt resource value: 1
			public const int RCCircleFlowIndicator_RCInactiveColor = 1;
			
			// aapt resource value: 6
			public const int RCCircleFlowIndicator_RCInactiveType = 6;
			
			// aapt resource value: 2
			public const int RCCircleFlowIndicator_RCRadius = 2;
			
			// aapt resource value: 8
			public const int RCCircleFlowIndicator_RCSnap = 8;
			
			// aapt resource value: 3
			public const int RCCircleFlowIndicator_RCSpacing = 3;
			
			public static int[] RCViewFlow = new int[] {
					2130771979};
			
			// aapt resource value: 0
			public const int RCViewFlow_RCSideBuffer = 0;
			
			public static int[] SideBarAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int SideBarAttrs_sidebar_letter_color = 2;
			
			// aapt resource value: 3
			public const int SideBarAttrs_sidebar_letter_color_selected = 3;
			
			// aapt resource value: 4
			public const int SideBarAttrs_sidebar_letter_size = 4;
			
			// aapt resource value: 5
			public const int SideBarAttrs_sidebar_selected_bg = 5;
			
			// aapt resource value: 0
			public const int SideBarAttrs_text_dialog_color = 0;
			
			// aapt resource value: 1
			public const int SideBarAttrs_text_dialog_size = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
